version: 2
updates:
  # Frontend dependencies
  - package-ecosystem: "npm"
    directory: "/web-app"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    assignees:
      - "meetingly-team"
    reviewers:
      - "meetingly-team"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "frontend"
    groups:
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security-update"
      minor-updates:
        patterns:
          - "*"
        update-types:
          - "version-update:semver-minor"
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "version-update:semver-patch"

  # Desktop app dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "meetingly-team"
    reviewers:
      - "meetingly-team"
    commit-message:
      prefix: "deps(desktop)"
      include: "scope"
    labels:
      - "dependencies"
      - "desktop"

  # Backend dependencies
  - package-ecosystem: "pip"
    directory: "/api"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    assignees:
      - "meetingly-team"
    reviewers:
      - "meetingly-team"
    commit-message:
      prefix: "deps(api)"
      include: "scope"
    labels:
      - "dependencies"
      - "backend"
    groups:
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security-update"
      minor-updates:
        patterns:
          - "*"
        update-types:
          - "version-update:semver-minor"

  # Shared types dependencies
  - package-ecosystem: "npm"
    directory: "/shared-types"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "meetingly-team"
    reviewers:
      - "meetingly-team"
    commit-message:
      prefix: "deps(types)"
      include: "scope"
    labels:
      - "dependencies"
      - "shared-types"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "meetingly-team"
    reviewers:
      - "meetingly-team"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/api"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "meetingly-team"
    reviewers:
      - "meetingly-team"
    commit-message:
      prefix: "deps(docker)"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"